### ISSUE TITLE
Latest executabel

### ISSUE THREAD

**Issue by Marcello1970** [vanBassum/StuffDatabase#1] opened 2021-01-05 16:58 UTC
Is it possible to publish also the latest executabel? I'm not capable to compile it myself.
Thanks!

**Comment by vanBassum** [comment] 2021-01-05 19:42
Sure, just wondering, why do you want to use this software? Not that I don't want you to use is, just wondering what you are expecting.

**Comment by Marcello1970** [comment] 2021-01-05 21:54
I had read about it on de circuitonline website. I got the boxes and dymo printer. So I can store my components. 
First I downloaded the version from CO, but that version gives an error.

**Comment by vanBassum** [comment] 2021-01-05 23:37
The application changes over time when I feel the need to add certain features. Let me know what you think.

**Comment by vanBassum** [comment] 2021-01-06 13:14
I just realized that you need some templates, Here is my database that you can use as an example.
[Resources.zip](https://github.com/vanBassum/StuffDatabase/files/5775936/Resources.zip)

**Comment by Marcello1970** [comment] 2021-01-06 15:56
Thank you, I thought something was missing. 
After adding your templates, I get the same error again. 

When I copy the file from the dymo map, it give an other error, it can't open small.label

************** Tekst van uitzondering **************
System.IO.FileNotFoundException: Kan bestand of assembly Interop.DYMOPrintingSupportLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5426002a38745af9 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
Bestandsnaam: Interop.DYMOPrintingSupportLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5426002a38745af9
   bij DYMO.DLS.Runtime.Printers.Init()
   bij DYMO.Label.Framework.Printers..ctor()
   bij StuffDatabase.Dymo.Render[T](Template`1 template, T comp) in C:\Workspace\VisualStudio\StuffDatabase\StuffDatabase\StuffDatabase\Dymo.cs:regel 11
   bij StuffDatabase.CTRL_Component.Render(BaseComponent component) in C:\Workspace\VisualStudio\StuffDatabase\StuffDatabase\StuffDatabase\CTRL_Component.cs:regel 182
   bij StuffDatabase.CTRL_Component.treeView1_AfterSelect(Object sender, TreeViewEventArgs e) in C:\Workspace\VisualStudio\StuffDatabase\StuffDatabase\StuffDatabase\CTRL_Component.cs:regel 174
   bij System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   bij System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   bij System.Windows.Forms.TreeView.WmNotify(Message& m)
   bij System.Windows.Forms.TreeView.WndProc(Message& m)
   bij System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bij System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bij System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by vanBassum** [comment] 2021-01-06 16:24
Ah I see, there is a reference missing to the DYMO library. I'll fix this and post a new release.

**Comment by vanBassum** [comment] 2021-01-06 17:12
Alright, this should fix the problem.
https://github.com/vanBassum/StuffDatabase/releases/tag/V01.00.01.00

**Comment by Marcello1970** [comment] 2021-01-06 17:34
Great, Can you publish the executable also? Then I will test it again.

**Comment by vanBassum** [comment] 2021-01-06 18:22
Oh my bad, I forgot to include the binaries. Just uploaded them. https://github.com/vanBassum/StuffDatabase/releases/tag/V01.00.01.00

**Comment by Marcello1970** [comment] 2021-01-06 20:12
Unfortunately, I am getting the following error:

`System.TypeInitializationException: De type-initialisatiefunctie voor DYMO.Managed.PrintingSupportGateway heeft een uitzondering veroorzaakt. ---> System.IO.FileNotFoundException: Kan bestand of assembly file:///C:\Apps\StuffDatabase\PrintingSupportLibrary.dll of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
   bij DYMO.Managed.PrintingSupportGateway..cctor()
   --- Einde van intern uitzonderingsstackpad ---
   bij DYMO.Managed.PrintingSupportGateway.GetPrinters()
   bij DYMO.DLS.Runtime.Printers.RetrieveInstalledPrinters()
   bij DYMO.DLS.Runtime.Printers.Init()
   bij DYMO.DLS.Runtime.Printers.GetEnumerator()
   bij System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij DYMO.Label.Framework.Printers..ctor()
   bij StuffDatabase.Dymo.Render[T](Template`1 template, T comp) in C:\Workspace\VisualStudio\StuffDatabase\StuffDatabase\StuffDatabase\Dymo.cs:regel 12
   bij StuffDatabase.CTRL_Component.Render(BaseComponent component) in C:\Workspace\VisualStudio\StuffDatabase\StuffDatabase\StuffDatabase\CTRL_Component.cs:regel 182
   bij StuffDatabase.CTRL_Component.treeView1_AfterSelect(Object sender, TreeViewEventArgs e) in C:\Workspace\VisualStudio\StuffDatabase\StuffDatabase\StuffDatabase\CTRL_Component.cs:regel 174
   bij System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   bij System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   bij System.Windows.Forms.TreeView.WmNotify(Message& m)
   bij System.Windows.Forms.TreeView.WndProc(Message& m)
   bij System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bij System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bij System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by vanBassum** [comment] 2021-01-06 23:54
Hmm, this makes it a bit more difficult since it does work on my pc. My best guess is that it has to do with the DYMO software I have installed. Tomorrow I'll see if I can reproduce this on my laptop, otherwise you might need to install the DYMO software as well. I'll keep you posted.

**Comment by Marcello1970** [comment] 2021-01-07 08:24
Thanks, I have both Dymo software installed, the Label and Connect. Both the latest versions. 
I have copied the file 'PrintingSupportLibrary.dll' to the map. And now I get the following error:

`************** Tekst van uitzondering **************
DYMO.DLS.Runtime.DlsRuntimeException: Unable to load label template 'data\Components\Resistor\Templates\Smallest.label' ---> System.InvalidOperationException: Het XML-document (15, 4) bevat een fout. ---> System.InvalidOperationException: Het XML-document (15, 4) bevat een fout. ---> System.InvalidOperationException: Het XML-document (15, 4) bevat een fout. ---> System.Reflection.TargetInvocationException: Het doel van een aanroep heeft een uitzondering veroorzaakt. ---> System.IO.FileNotFoundException: Kan bestand of assembly file:///C:\Apps\StuffDatabase\MDYMOBarcode.dll of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
   bij DYMO.DLS.Runtime.BarcodeLib..ctor()
   bij DYMO.DLS.Runtime.BarcodeRenderer..ctor(BarcodeType type, String text, BarcodeSize barcodeSize, HumanReadablePosition hrtPosition, Int32 ecLevel)
   bij DYMO.DLS.Runtime.AddressObject..ctor()
   --- Einde van intern uitzonderingsstackpad ---`

**Comment by vanBassum** [comment] 2021-01-07 13:48
I have seen that before, the problem was that the version of the dll was wrong. I'll attach a zipfile of all the DLL's in my DYMO folder. Furthermore, I can see in the error that you also need 'MDYMOBarcode.dll' Can you try these and get back to me with the results? Then I can add the DLL's to the release should anyone else want to use this software.

[DYMO DLL's.zip](https://github.com/vanBassum/StuffDatabase/files/5781919/DYMO.DLL.s.zip)

**Comment by Marcello1970** [comment] 2021-01-07 14:38
It works, eventually i had to add 3 dll files by hand. 
MDYMOBarcode.dll did not existed on my PC, so I took yours.
DYMOPrinting.dll, PrintingSupportLibrary.dll where in my Dymo connect map, So i copied them into the stuffDatabase map. 

I will make a new issue for the IC tab. First I will think about the options.

**Comment by vanBassum** [comment] 2021-01-07 14:43
Awesome, I'll include these DLL's in the next release. Have you figured out how to change the labels yet? Maybe some documentation from my part is necessary. However, I'll close this Item now since it's fixed. Let me know If you require more help.

**Closed by vanBassum** 2021-01-07 14:43 UTC
